### ISSUE TITLE
Issue 1: Parsing Issue of CSVs in save-to-csv.ipynb

### ISSUE THREAD

**Issue by edebroux** [twitter-fire-scraper-analytics/twitter-fire-scraper#2]
Every tweet that is stored as a CSV of any sort of punctuation mark delimiter (like a comma or a semi-colon) has a chance of showing up in a tweet. This becomes an issue when we try to tokenize the tweet by loading it to our models in Python. Since the tweet has a delimiter in its content field we get an error such as:

```python
ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2
```

A solution to this would be creating a function that tokenizes the punctuation marks and emoticons in each tweet.

**Comment by HenryFBP** [comment]
Added in bdd494c2b56b171039c5c7b5dac440ecfac15a18
